# Look in the tasks/setup.rb file for the various options that can be
# configured in this Rakefile. The .rake files in the tasks directory
# are where the options are used.

begin
  require 'bones'
  Bones.setup
rescue LoadError
  begin
    load 'tasks/setup.rb'
  rescue LoadError
    raise RuntimeError, '### please install the "bones" gem ###'
  end
end

ensure_in_path 'lib'
require 'p4rally'

task :default => 'spec:run'

PROJ.name = 'p4rally'
PROJ.authors = 'Sam Beran'
PROJ.email = 'sberan@gmail.com'
PROJ.url = 'http://wiki.github.com/sberan/P4Rally'
PROJ.version = P4rally::VERSION
PROJ.rubyforge.name = 'p4rally'

PROJ.spec.opts << '--color'

# EOF
